package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Guestbook;
import cn.freeteam.cms.model.GuestbookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuestbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int countByExample(GuestbookExample example);
    int countByExampleCache(GuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int deleteByExample(GuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int insert(Guestbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int insertSelective(Guestbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    List<Guestbook> selectByExample(GuestbookExample example);
    List<Guestbook> selectPageByExample(GuestbookExample example);
    List<Guestbook> selectPageByExampleCache(GuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    Guestbook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int updateByExampleSelective(@Param("record") Guestbook record, @Param("example") GuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int updateByExample(@Param("record") Guestbook record, @Param("example") GuestbookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int updateByPrimaryKeySelective(Guestbook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_guestbook
     *
     * @mbggenerated Wed Jun 26 15:08:45 CST 2013
     */
    int updateByPrimaryKey(Guestbook record);
}