package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.MembergroupAtuh;
import cn.freeteam.cms.model.MembergroupAtuhExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MembergroupAtuhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int countByExample(MembergroupAtuhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int deleteByExample(MembergroupAtuhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int insert(MembergroupAtuh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int insertSelective(MembergroupAtuh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    List<MembergroupAtuh> selectByExample(MembergroupAtuhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    MembergroupAtuh selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int updateByExampleSelective(@Param("record") MembergroupAtuh record, @Param("example") MembergroupAtuhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int updateByExample(@Param("record") MembergroupAtuh record, @Param("example") MembergroupAtuhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int updateByPrimaryKeySelective(MembergroupAtuh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_atuh
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    int updateByPrimaryKey(MembergroupAtuh record);
}