package cn.freeteam.cms.model;

public class Creditrule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.id
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.code
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.name
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.orderNum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.rewardtype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer rewardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.cycletype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer cycletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.cycletime
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer cycletime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.rewardnum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer rewardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.credit
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_creditrule.experience
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    private Integer experience;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.id
     *
     * @return the value of freecms_creditrule.id
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.id
     *
     * @param id the value for freecms_creditrule.id
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.code
     *
     * @return the value of freecms_creditrule.code
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.code
     *
     * @param code the value for freecms_creditrule.code
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.name
     *
     * @return the value of freecms_creditrule.name
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.name
     *
     * @param name the value for freecms_creditrule.name
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.orderNum
     *
     * @return the value of freecms_creditrule.orderNum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.orderNum
     *
     * @param ordernum the value for freecms_creditrule.orderNum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.rewardtype
     *
     * @return the value of freecms_creditrule.rewardtype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getRewardtype() {
        return rewardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.rewardtype
     *
     * @param rewardtype the value for freecms_creditrule.rewardtype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setRewardtype(Integer rewardtype) {
        this.rewardtype = rewardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.cycletype
     *
     * @return the value of freecms_creditrule.cycletype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getCycletype() {
        return cycletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.cycletype
     *
     * @param cycletype the value for freecms_creditrule.cycletype
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setCycletype(Integer cycletype) {
        this.cycletype = cycletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.cycletime
     *
     * @return the value of freecms_creditrule.cycletime
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getCycletime() {
        return cycletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.cycletime
     *
     * @param cycletime the value for freecms_creditrule.cycletime
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setCycletime(Integer cycletime) {
        this.cycletime = cycletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.rewardnum
     *
     * @return the value of freecms_creditrule.rewardnum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getRewardnum() {
        return rewardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.rewardnum
     *
     * @param rewardnum the value for freecms_creditrule.rewardnum
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setRewardnum(Integer rewardnum) {
        this.rewardnum = rewardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.credit
     *
     * @return the value of freecms_creditrule.credit
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.credit
     *
     * @param credit the value for freecms_creditrule.credit
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_creditrule.experience
     *
     * @return the value of freecms_creditrule.experience
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_creditrule.experience
     *
     * @param experience the value for freecms_creditrule.experience
     *
     * @mbggenerated Mon Feb 04 19:47:47 CST 2013
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }
}