package cn.freeteam.cms.model;

import java.util.Date;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.id
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.memberid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.siteid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.sitename
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String sitename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.channelid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.channelname
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String channelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.objtype
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String objtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.objid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String objid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.objtitle
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private String objtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_store.storetime
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    private Date storetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.id
     *
     * @return the value of freecms_store.id
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.id
     *
     * @param id the value for freecms_store.id
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.memberid
     *
     * @return the value of freecms_store.memberid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.memberid
     *
     * @param memberid the value for freecms_store.memberid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.siteid
     *
     * @return the value of freecms_store.siteid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.siteid
     *
     * @param siteid the value for freecms_store.siteid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid == null ? null : siteid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.sitename
     *
     * @return the value of freecms_store.sitename
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.sitename
     *
     * @param sitename the value for freecms_store.sitename
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.channelid
     *
     * @return the value of freecms_store.channelid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.channelid
     *
     * @param channelid the value for freecms_store.channelid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.channelname
     *
     * @return the value of freecms_store.channelname
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getChannelname() {
        return channelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.channelname
     *
     * @param channelname the value for freecms_store.channelname
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setChannelname(String channelname) {
        this.channelname = channelname == null ? null : channelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.objtype
     *
     * @return the value of freecms_store.objtype
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getObjtype() {
        return objtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.objtype
     *
     * @param objtype the value for freecms_store.objtype
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setObjtype(String objtype) {
        this.objtype = objtype == null ? null : objtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.objid
     *
     * @return the value of freecms_store.objid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getObjid() {
        return objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.objid
     *
     * @param objid the value for freecms_store.objid
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setObjid(String objid) {
        this.objid = objid == null ? null : objid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.objtitle
     *
     * @return the value of freecms_store.objtitle
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public String getObjtitle() {
        return objtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.objtitle
     *
     * @param objtitle the value for freecms_store.objtitle
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setObjtitle(String objtitle) {
        this.objtitle = objtitle == null ? null : objtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_store.storetime
     *
     * @return the value of freecms_store.storetime
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public Date getStoretime() {
        return storetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_store.storetime
     *
     * @param storetime the value for freecms_store.storetime
     *
     * @mbggenerated Tue Jul 02 09:29:46 CST 2013
     */
    public void setStoretime(Date storetime) {
        this.storetime = storetime;
    }
}