package cn.freeteam.cms.model;

public class MembergroupAtuh {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_membergroup_atuh.id
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_membergroup_atuh.groupid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_membergroup_atuh.authid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    private String authid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_membergroup_atuh.id
     *
     * @return the value of freecms_membergroup_atuh.id
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_membergroup_atuh.id
     *
     * @param id the value for freecms_membergroup_atuh.id
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_membergroup_atuh.groupid
     *
     * @return the value of freecms_membergroup_atuh.groupid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_membergroup_atuh.groupid
     *
     * @param groupid the value for freecms_membergroup_atuh.groupid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_membergroup_atuh.authid
     *
     * @return the value of freecms_membergroup_atuh.authid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public String getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_membergroup_atuh.authid
     *
     * @param authid the value for freecms_membergroup_atuh.authid
     *
     * @mbggenerated Fri Feb 01 15:49:14 CST 2013
     */
    public void setAuthid(String authid) {
        this.authid = authid == null ? null : authid.trim();
    }
}