package cn.freeteam.cms.model;

import java.util.Date;

public class Visit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.id
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.url
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.id
     *
     * @return the value of freecms_visit.id
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.id
     *
     * @param id the value for freecms_visit.id
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.siteid
     *
     * @return the value of freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.siteid
     *
     * @param siteid the value for freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid == null ? null : siteid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.channelid
     *
     * @return the value of freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.channelid
     *
     * @param channelid the value for freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.infoid
     *
     * @return the value of freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.infoid
     *
     * @param infoid the value for freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid == null ? null : infoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.url
     *
     * @return the value of freecms_visit.url
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.url
     *
     * @param url the value for freecms_visit.url
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.addtime
     *
     * @return the value of freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.addtime
     *
     * @param addtime the value for freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 15:23:06 CST 2013
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}